import os

BOT_NAME = "crasp_spider"

SPIDER_MODULES = ["crasp_spider.spiders"]
NEWSPIDER_MODULE = "crasp_spider.spiders"

ROBOTSTXT_OBEY = False

FEED_URI = os.environ.get("CRASP_FEED_URI", "")
if FEED_URI:
    FEEDS = {FEED_URI: {"format": "jsonlines"}}
else:
    FEEDS = {}

REQUEST_FINGERPRINTER_IMPLEMENTATION = "2.7"
TWISTED_REACTOR = "twisted.internet.asyncioreactor.AsyncioSelectorReactor"

CONCURRENT_REQUESTS = 8
DOWNLOAD_TIMEOUT = 30

AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 1.0
AUTOTHROTTLE_MAX_DELAY = 30.0
AUTOTHROTTLE_TARGET_CONCURRENCY = 1.0
AUTOTHROTTLE_DEBUG = False

DOWNLOAD_DELAY = 0.5
CONCURRENT_REQUESTS_PER_DOMAIN = 1

LOG_LEVEL = "INFO"
